version: '3.7'
services:
    web:
        container_name: docker_hub_web_v5_test
        image: "bigtincan/chrome-nodejs-amazon-linux"
        user: ${userid}:${groupid}
        working_dir: /app
        stdin_open: true
        volumes:
            - ${PWD}:/app
        tty: true
        cap_add:
            - SYS_ADMIN
        command: /app/scripts/test.sh