version: '3.7'
services:
    web:
        container_name: docker_build
        image: "node:lts"
        user: ${userid}:${groupid}
        working_dir: /app
        stdin_open: true
        volumes:
            - ${PWD}:/app
        tty: true
        cap_add:
            - SYS_ADMIN
        command: /app/scripts/build.sh
