apiVersion: v1
kind: Pod
metadata:
  labels:
    app: hub-webapp-v5-kaniko
spec:
  serviceAccountName: jenkins-sa
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      imagePullPolicy: Always
      resources:
        requests:
          memory: "2048Mi"
          cpu: "500m"
      command:
        - /busybox/cat
      tty: true
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker/
    - name: curl
      image: alpine
      command:
        - cat
      tty: true
  volumes:
    - name: docker-config
      configMap:
        name: docker-config
