apiVersion: v1
kind: Pod
metadata:
  labels:
    app: hub-webapp-v5-test
spec:
  serviceAccountName: jenkins-sa
  containers:
    - name: test
      image: bigtincan/chrome-nodejs-amazon-linux
      imagePullPolicy: Always
      resources:
        requests:
          memory: "2048Mi"
          cpu: "1000m"
      command:
        - cat
      tty: true
